# Dockerfile for building openresty-brotli for Debian / Ubuntu
#
# Usage :
#
#   docker build -t build-openresty-brotli -f Dockerfile-deb \
#       --build-arg DISTRIB=debian --build-arg RELEASE=stretch \
#       --build-arg OPENRESTY_VERSION=1.18.0 .
#
# Or Ubuntu :
#
#   docker build -t build-openresty-brotli -f Dockerfile-deb \
#       --build-arg DISTRIB=ubuntu --build-arg RELEASE=bionic \
#       --build-arg OPENRESTY_VERSION=1.18.0 .
#
# Then :
#
#   docker run build-openresty-brotli
#   docker cp $(docker ps -l -q):/src ~/Downloads/
# And once you don't need it anymore :
#   docker rm $(docker ps -l -q)
#
# Latest ngx_brotli version : https://github.com/google/ngx_brotli
#
# Latest openresty version : https://openresty.org/en/download.html
# Or :
# curl -s https://openresty.org/package/debian/pool/openresty/o/openresty/ |grep '"openresty_' | sed -n "s/^.*\">openresty_\(.*\)\~.*$/\1/p" |sort -Vr |head -1| cut -d'-' -f1

ARG DISTRIB=debian
ARG RELEASE=stretch

FROM ${DISTRIB}:${RELEASE}
MAINTAINER Jukka Raimovaara "roska@mentalhouse.fi"

ARG DISTRIB
ARG RELEASE
#ARG CHANGELOG_MSG
ARG DEBIAN_FRONTEND="noninteractive"
ENV TZ=Europe/Helsinki

RUN apt-get update && apt-get --no-install-recommends --no-install-suggests -y install \
    git wget ca-certificates curl openssl gnupg2 apt-transport-https \
    unzip make libpcre3-dev zlib1g-dev build-essential devscripts \
    debhelper quilt lsb-release libssl-dev lintian uuid-dev

ARG OPENRESTY_VERSION=1.19.3.1
ARG OPENRESTY_DEB_RELEASE=1
ARG BROTLI_VERSION=1.0.9

WORKDIR /root

RUN git clone --depth=1 https://github.com/google/ngx_brotli.git && cd ngx_brotli && git submodule update --init --recursive --recommend-shallow --depth 1
RUN wget -qO - https://openresty.org/download/openresty-${OPENRESTY_VERSION}.tar.gz | tar zxf -

COPY debian openresty-${OPENRESTY_VERSION}/debian

RUN sed -i "s/stretch; urgency/${RELEASE}; urgency/g" openresty-${OPENRESTY_VERSION}/debian/changelog
RUN sed -i "s/~stretch)/~${RELEASE})/g" openresty-${OPENRESTY_VERSION}/debian/changelog
RUN sed -i "s/{OPENRESTY_VERSION}/${OPENRESTY_VERSION}-${OPENRESTY_DEB_RELEASE}~${RELEASE}${OPENRESTY_DEB_RELEASE}/g" openresty-${OPENRESTY_VERSION}/debian/control

RUN cd openresty-${OPENRESTY_VERSION} && dpkg-buildpackage --jobs=auto

RUN mkdir /src && mv openresty-brotli* /src/ && cp openresty-${OPENRESTY_VERSION}/debian/changelog /src/
RUN dpkg -c /src/openresty-brotli_*.deb

RUN curl -L https://openresty.org/package/pubkey.gpg | apt-key add -
RUN echo "deb http://openresty.org/package/${DISTRIB}/ ${RELEASE} openresty" >> /etc/apt/sources.list.d/openresty.list

RUN apt-get update && apt-get -V --no-install-recommends --no-install-suggests -y install openresty=${OPENRESTY_VERSION}-${OPENRESTY_DEB_RELEASE}~${RELEASE}${OPENRESTY_DEB_RELEASE}

RUN dpkg -i /src/openresty-brotli_*.deb && \
    sed -i '1iload_module /etc/openresty/modules/ngx_http_brotli_filter_module.so;' /etc/openresty/nginx.conf && \
    sed -i 's/#gzip  on;/brotli on;/' /etc/openresty/nginx.conf && \
    openresty -t && /etc/init.d/openresty start && echo "Testing Openresty headers for Brotli presence : " && \
    curl -s -I -H 'Accept-Encoding: br,gzip,deflate' http://localhost/ |grep 'Content-Encoding: br'

RUN dpkg -r openresty-brotli
RUN dpkg -P openresty-brotli
